import type {
  DistribucionPerfil,
  Empresa,
  Municipio,
  Oportunidad,
  Perfil,
  PuntoSerie,
  ZonaActividad,
} from "./types"

// Datos mock realistas. Al conectar Airtable, este archivo se sustituye por
// las llamadas a la API; la forma de los datos se mantiene igual.

const ahora = Date.UTC(2026, 8, 8, 12, 0, 0) // referencia estable para "hace X"

const hace = (minutos: number) => new Date(ahora - minutos * 60_000).toISOString()

export const oportunidades: Oportunidad[] = [
  {
    id: "opp_001",
    titulo: "Camarero/a de sala",
    empresa: "Grupo Mediterráneo",
    perfil: "Camarero/a",
    tipoPerfil: "Camareros",
    municipio: "Alicante",
    provincia: "Alicante",
    zona: "Alicante",
    urlOferta: "https://ejemplo.com/oferta/001",
    fuente: "InfoJobs",
    fechaPublicacion: hace(30),
    fechaDeteccion: hace(12),
    estado: "Nueva",
    prioridad: "Alta",
  },
  {
    id: "opp_002",
    titulo: "Peón agrícola",
    empresa: "Agrícola Levante S.L.",
    perfil: "Peón agrícola",
    tipoPerfil: "Agricultura",
    municipio: "Elche",
    provincia: "Alicante",
    zona: "Elche",
    urlOferta: "https://ejemplo.com/oferta/002",
    fuente: "Milanuncios",
    fechaPublicacion: hace(60),
    fechaDeteccion: hace(26),
    estado: "Nueva",
    prioridad: "Media",
  },
  {
    id: "opp_003",
    titulo: "Cocinero/a",
    empresa: "Hotel Costa Blanca",
    perfil: "Cocinero/a",
    tipoPerfil: "Cocineros",
    municipio: "Benidorm",
    provincia: "Alicante",
    zona: "Alicante",
    urlOferta: "https://ejemplo.com/oferta/003",
    fuente: "LinkedIn",
    fechaPublicacion: hace(120),
    fechaDeteccion: hace(60),
    estado: "Revisada",
    prioridad: "Alta",
  },
  {
    id: "opp_004",
    titulo: "Mozo/a de almacén",
    empresa: "Logística Vega Sur",
    perfil: "Mozo/a de almacén",
    tipoPerfil: "Almacén",
    municipio: "Orihuela",
    provincia: "Alicante",
    zona: "Orihuela",
    urlOferta: "https://ejemplo.com/oferta/004",
    fuente: "InfoJobs",
    fechaPublicacion: hace(180),
    fechaDeteccion: hace(120),
    estado: "Contactada",
    prioridad: "Media",
  },
  {
    id: "opp_005",
    titulo: "Peón de construcción",
    empresa: "Construcciones Levante",
    perfil: "Peón construcción",
    tipoPerfil: "Construcción",
    municipio: "Murcia",
    provincia: "Murcia",
    zona: "Murcia",
    urlOferta: "https://ejemplo.com/oferta/005",
    fuente: "Indeed",
    fechaPublicacion: hace(200),
    fechaDeteccion: hace(180),
    estado: "Nueva",
    prioridad: "Alta",
  },
  {
    id: "opp_006",
    titulo: "Personal de limpieza",
    empresa: "Limpiezas Sol y Mar",
    perfil: "Limpiador/a",
    tipoPerfil: "Limpieza",
    municipio: "Alicante",
    provincia: "Alicante",
    zona: "Alicante",
    urlOferta: "https://ejemplo.com/oferta/006",
    fuente: "InfoJobs",
    fechaPublicacion: hace(260),
    fechaDeteccion: hace(240),
    estado: "Interesante",
    prioridad: "Media",
  },
  {
    id: "opp_007",
    titulo: "Administrativo/a contable",
    empresa: "Gestoría Alba",
    perfil: "Administrativo/a",
    tipoPerfil: "Administrativos",
    municipio: "Elche",
    provincia: "Alicante",
    zona: "Elche",
    urlOferta: "https://ejemplo.com/oferta/007",
    fuente: "LinkedIn",
    fechaPublicacion: hace(300),
    fechaDeteccion: hace(280),
    estado: "Revisada",
    prioridad: "Baja",
  },
  {
    id: "opp_008",
    titulo: "Dependiente/a de tienda",
    empresa: "Moda Levante",
    perfil: "Dependiente/a",
    tipoPerfil: "Dependientes",
    municipio: "Valencia",
    provincia: "Valencia",
    zona: "Valencia",
    urlOferta: "https://ejemplo.com/oferta/008",
    fuente: "Indeed",
    fechaPublicacion: hace(360),
    fechaDeteccion: hace(320),
    estado: "Nueva",
    prioridad: "Media",
  },
  {
    id: "opp_009",
    titulo: "Ayudante de cocina",
    empresa: "Restaurante El Puerto",
    perfil: "Ayudante de cocina",
    tipoPerfil: "Cocineros",
    municipio: "Alicante",
    provincia: "Alicante",
    zona: "Alicante",
    urlOferta: "https://ejemplo.com/oferta/009",
    fuente: "InfoJobs",
    fechaPublicacion: hace(420),
    fechaDeteccion: hace(400),
    estado: "Contactada",
    prioridad: "Media",
  },
  {
    id: "opp_010",
    titulo: "Camarero/a de barra",
    empresa: "Cervecería Central",
    perfil: "Camarero/a",
    tipoPerfil: "Camareros",
    municipio: "Murcia",
    provincia: "Murcia",
    zona: "Murcia",
    urlOferta: "https://ejemplo.com/oferta/010",
    fuente: "Milanuncios",
    fechaPublicacion: hace(500),
    fechaDeteccion: hace(480),
    estado: "Nueva",
    prioridad: "Alta",
  },
  {
    id: "opp_011",
    titulo: "Operario/a de almacén",
    empresa: "Distribuciones Segura",
    perfil: "Operario/a",
    tipoPerfil: "Almacén",
    municipio: "Orihuela",
    provincia: "Alicante",
    zona: "Orihuela",
    urlOferta: "https://ejemplo.com/oferta/011",
    fuente: "Indeed",
    fechaPublicacion: hace(600),
    fechaDeteccion: hace(580),
    estado: "Revisada",
    prioridad: "Baja",
  },
  {
    id: "opp_012",
    titulo: "Recolector/a de cítricos",
    empresa: "Cítricos del Segura",
    perfil: "Peón agrícola",
    tipoPerfil: "Agricultura",
    municipio: "Orihuela",
    provincia: "Alicante",
    zona: "Orihuela",
    urlOferta: "https://ejemplo.com/oferta/012",
    fuente: "Milanuncios",
    fechaPublicacion: hace(720),
    fechaDeteccion: hace(700),
    estado: "Interesante",
    prioridad: "Alta",
  },
  {
    id: "opp_013",
    titulo: "Encargado/a de limpieza",
    empresa: "Higiene Profesional Vega",
    perfil: "Encargado/a",
    tipoPerfil: "Limpieza",
    municipio: "Elche",
    provincia: "Alicante",
    zona: "Elche",
    urlOferta: "https://ejemplo.com/oferta/013",
    fuente: "InfoJobs",
    fechaPublicacion: hace(900),
    fechaDeteccion: hace(880),
    estado: "Nueva",
    prioridad: "Media",
  },
  {
    id: "opp_014",
    titulo: "Recepcionista de hotel",
    empresa: "Hotel Marina Azul",
    perfil: "Recepcionista",
    tipoPerfil: "Administrativos",
    municipio: "Benidorm",
    provincia: "Alicante",
    zona: "Alicante",
    urlOferta: "https://ejemplo.com/oferta/014",
    fuente: "LinkedIn",
    fechaPublicacion: hace(1000),
    fechaDeteccion: hace(980),
    estado: "Contactada",
    prioridad: "Media",
  },
  {
    id: "opp_015",
    titulo: "Peón de obra",
    empresa: "Edificaciones Sur",
    perfil: "Peón construcción",
    tipoPerfil: "Construcción",
    municipio: "Valencia",
    provincia: "Valencia",
    zona: "Valencia",
    urlOferta: "https://ejemplo.com/oferta/015",
    fuente: "Indeed",
    fechaPublicacion: hace(1200),
    fechaDeteccion: hace(1180),
    estado: "Descartada",
    prioridad: "Baja",
  },
  {
    id: "opp_016",
    titulo: "Camarero/a de eventos",
    empresa: "Catering Mediterráneo",
    perfil: "Camarero/a",
    tipoPerfil: "Camareros",
    municipio: "Alicante",
    provincia: "Alicante",
    zona: "Alicante",
    urlOferta: "https://ejemplo.com/oferta/016",
    fuente: "InfoJobs",
    fechaPublicacion: hace(1400),
    fechaDeteccion: hace(1380),
    estado: "Nueva",
    prioridad: "Alta",
  },
  {
    id: "opp_017",
    titulo: "Mozo/a de carga y descarga",
    empresa: "Transportes Alicante",
    perfil: "Mozo/a",
    tipoPerfil: "Almacén",
    municipio: "Alicante",
    provincia: "Alicante",
    zona: "Alicante",
    urlOferta: "https://ejemplo.com/oferta/017",
    fuente: "Milanuncios",
    fechaPublicacion: hace(1600),
    fechaDeteccion: hace(1580),
    estado: "Revisada",
    prioridad: "Media",
  },
  {
    id: "opp_018",
    titulo: "Dependiente/a de supermercado",
    empresa: "Supermercados Vega",
    perfil: "Dependiente/a",
    tipoPerfil: "Dependientes",
    municipio: "Elche",
    provincia: "Alicante",
    zona: "Elche",
    urlOferta: "https://ejemplo.com/oferta/018",
    fuente: "Indeed",
    fechaPublicacion: hace(1800),
    fechaDeteccion: hace(1780),
    estado: "Nueva",
    prioridad: "Media",
  },
  {
    id: "opp_019",
    titulo: "Cocinero/a de línea",
    empresa: "Grupo Gastronómico Sur",
    perfil: "Cocinero/a",
    tipoPerfil: "Cocineros",
    municipio: "Murcia",
    provincia: "Murcia",
    zona: "Murcia",
    urlOferta: "https://ejemplo.com/oferta/019",
    fuente: "LinkedIn",
    fechaPublicacion: hace(2000),
    fechaDeteccion: hace(1980),
    estado: "Interesante",
    prioridad: "Alta",
  },
  {
    id: "opp_020",
    titulo: "Auxiliar administrativo/a",
    empresa: "Asesoría Costa",
    perfil: "Administrativo/a",
    tipoPerfil: "Administrativos",
    municipio: "Valencia",
    provincia: "Valencia",
    zona: "Valencia",
    urlOferta: "https://ejemplo.com/oferta/020",
    fuente: "InfoJobs",
    fechaPublicacion: hace(2400),
    fechaDeteccion: hace(2380),
    estado: "Contactada",
    prioridad: "Baja",
  },
  {
    id: "opp_021",
    titulo: "Personal de limpieza industrial",
    empresa: "Servicios Vega",
    perfil: "Limpiador/a",
    tipoPerfil: "Limpieza",
    municipio: "Murcia",
    provincia: "Murcia",
    zona: "Murcia",
    urlOferta: "https://ejemplo.com/oferta/021",
    fuente: "Indeed",
    fechaPublicacion: hace(2800),
    fechaDeteccion: hace(2780),
    estado: "Nueva",
    prioridad: "Media",
  },
  {
    id: "opp_022",
    titulo: "Peón agrícola de temporada",
    empresa: "Frutas del Mediterráneo",
    perfil: "Peón agrícola",
    tipoPerfil: "Agricultura",
    municipio: "Elche",
    provincia: "Alicante",
    zona: "Elche",
    urlOferta: "https://ejemplo.com/oferta/022",
    fuente: "Milanuncios",
    fechaPublicacion: hace(3200),
    fechaDeteccion: hace(3180),
    estado: "Revisada",
    prioridad: "Alta",
  },
  {
    id: "opp_023",
    titulo: "Ayudante de camarero/a",
    empresa: "Chiringuito Playa Norte",
    perfil: "Ayudante",
    tipoPerfil: "Camareros",
    municipio: "Valencia",
    provincia: "Valencia",
    zona: "Valencia",
    urlOferta: "https://ejemplo.com/oferta/023",
    fuente: "InfoJobs",
    fechaPublicacion: hace(3600),
    fechaDeteccion: hace(3580),
    estado: "Nueva",
    prioridad: "Media",
  },
  {
    id: "opp_024",
    titulo: "Repartidor/a con carné",
    empresa: "Mensajería Rápida Sur",
    perfil: "Repartidor/a",
    tipoPerfil: "Otros",
    municipio: "Alicante",
    provincia: "Alicante",
    zona: "Alicante",
    urlOferta: "https://ejemplo.com/oferta/024",
    fuente: "Indeed",
    fechaPublicacion: hace(4000),
    fechaDeteccion: hace(3980),
    estado: "Descartada",
    prioridad: "Baja",
  },
]

export const empresas: Empresa[] = [
  {
    id: "emp_001",
    nombre: "Grupo Mediterráneo",
    web: "grupomediterraneo.es",
    telefono: "965 12 34 56",
    email: "rrhh@grupomediterraneo.es",
    municipio: "Alicante",
    provincia: "Alicante",
    sector: "Hostelería",
    oportunidades: 6,
    estadoComercial: "En seguimiento",
    ultimaActividad: hace(12),
  },
  {
    id: "emp_002",
    nombre: "Agrícola Levante S.L.",
    web: "agricolalevante.com",
    telefono: "966 45 78 90",
    email: "empleo@agricolalevante.com",
    municipio: "Elche",
    provincia: "Alicante",
    sector: "Agricultura",
    oportunidades: 4,
    estadoComercial: "Sin contactar",
    ultimaActividad: hace(26),
  },
  {
    id: "emp_003",
    nombre: "Hotel Costa Blanca",
    web: "hotelcostablanca.es",
    telefono: "965 88 77 66",
    email: "seleccion@hotelcostablanca.es",
    municipio: "Benidorm",
    provincia: "Alicante",
    sector: "Hostelería",
    oportunidades: 5,
    estadoComercial: "Cliente",
    ultimaActividad: hace(60),
  },
  {
    id: "emp_004",
    nombre: "Logística Vega Sur",
    web: "logisticavegasur.com",
    telefono: "968 23 45 67",
    email: "rrhh@logisticavegasur.com",
    municipio: "Orihuela",
    provincia: "Alicante",
    sector: "Logística",
    oportunidades: 3,
    estadoComercial: "En seguimiento",
    ultimaActividad: hace(120),
  },
  {
    id: "emp_005",
    nombre: "Construcciones Levante",
    web: "construccioneslevante.es",
    telefono: "968 34 56 78",
    email: "empleo@construccioneslevante.es",
    municipio: "Murcia",
    provincia: "Murcia",
    sector: "Construcción",
    oportunidades: 4,
    estadoComercial: "Sin contactar",
    ultimaActividad: hace(180),
  },
  {
    id: "emp_006",
    nombre: "Limpiezas Sol y Mar",
    web: "limpiezassolymar.com",
    telefono: "965 11 22 33",
    email: "info@limpiezassolymar.com",
    municipio: "Alicante",
    provincia: "Alicante",
    sector: "Servicios",
    oportunidades: 2,
    estadoComercial: "En seguimiento",
    ultimaActividad: hace(240),
  },
  {
    id: "emp_007",
    nombre: "Gestoría Alba",
    web: "gestoriaalba.es",
    telefono: "966 55 44 33",
    email: "contacto@gestoriaalba.es",
    municipio: "Elche",
    provincia: "Alicante",
    sector: "Servicios",
    oportunidades: 1,
    estadoComercial: "Sin contactar",
    ultimaActividad: hace(280),
  },
  {
    id: "emp_008",
    nombre: "Moda Levante",
    web: "modalevante.com",
    telefono: "963 22 11 44",
    email: "rrhh@modalevante.com",
    municipio: "Valencia",
    provincia: "Valencia",
    sector: "Comercio",
    oportunidades: 2,
    estadoComercial: "Sin contactar",
    ultimaActividad: hace(320),
  },
  {
    id: "emp_009",
    nombre: "Cítricos del Segura",
    web: "citricosdelsegura.es",
    telefono: "968 77 88 99",
    email: "empleo@citricosdelsegura.es",
    municipio: "Orihuela",
    provincia: "Alicante",
    sector: "Agricultura",
    oportunidades: 3,
    estadoComercial: "En seguimiento",
    ultimaActividad: hace(700),
  },
  {
    id: "emp_010",
    nombre: "Distribuciones Segura",
    web: "distribucionessegura.com",
    telefono: "968 66 55 44",
    email: "rrhh@distribucionessegura.com",
    municipio: "Orihuela",
    provincia: "Alicante",
    sector: "Logística",
    oportunidades: 2,
    estadoComercial: "Cliente",
    ultimaActividad: hace(580),
  },
  {
    id: "emp_011",
    nombre: "Catering Mediterráneo",
    web: "cateringmediterraneo.es",
    telefono: "965 99 88 77",
    email: "seleccion@cateringmediterraneo.es",
    municipio: "Alicante",
    provincia: "Alicante",
    sector: "Hostelería",
    oportunidades: 3,
    estadoComercial: "En seguimiento",
    ultimaActividad: hace(1380),
  },
  {
    id: "emp_012",
    nombre: "Supermercados Vega",
    web: "supermercadosvega.com",
    telefono: "966 33 22 11",
    email: "empleo@supermercadosvega.com",
    municipio: "Elche",
    provincia: "Alicante",
    sector: "Comercio",
    oportunidades: 2,
    estadoComercial: "Sin contactar",
    ultimaActividad: hace(1780),
  },
  {
    id: "emp_013",
    nombre: "Grupo Gastronómico Sur",
    web: "grupogastronomicosur.es",
    telefono: "968 44 33 22",
    email: "rrhh@grupogastronomicosur.es",
    municipio: "Murcia",
    provincia: "Murcia",
    sector: "Hostelería",
    oportunidades: 4,
    estadoComercial: "Cliente",
    ultimaActividad: hace(1980),
  },
  {
    id: "emp_014",
    nombre: "Frutas del Mediterráneo",
    web: "frutasmediterraneo.com",
    telefono: "966 22 33 44",
    email: "temporada@frutasmediterraneo.com",
    municipio: "Elche",
    provincia: "Alicante",
    sector: "Agricultura",
    oportunidades: 5,
    estadoComercial: "En seguimiento",
    ultimaActividad: hace(3180),
  },
]

export const perfiles: Perfil[] = [
  { id: "per_001", nombre: "Limpieza", activo: true },
  { id: "per_002", nombre: "Camareros", activo: true },
  { id: "per_003", nombre: "Cocineros", activo: true },
  { id: "per_004", nombre: "Administrativos", activo: true },
  { id: "per_005", nombre: "Almacén", activo: true },
  { id: "per_006", nombre: "Dependientes", activo: true },
  { id: "per_007", nombre: "Agricultura", activo: true },
  { id: "per_008", nombre: "Construcción", activo: true },
  { id: "per_009", nombre: "Otros", activo: false },
]

export const municipios: Municipio[] = [
  { id: "mun_001", municipio: "Alicante", provincia: "Alicante", zona: "Alicante", activo: true },
  { id: "mun_002", municipio: "Elche", provincia: "Alicante", zona: "Elche", activo: true },
  { id: "mun_003", municipio: "Orihuela", provincia: "Alicante", zona: "Orihuela", activo: true },
  { id: "mun_004", municipio: "Benidorm", provincia: "Alicante", zona: "Alicante", activo: true },
  { id: "mun_005", municipio: "Murcia", provincia: "Murcia", zona: "Murcia", activo: true },
  { id: "mun_006", municipio: "Valencia", provincia: "Valencia", zona: "Valencia", activo: true },
  { id: "mun_007", municipio: "Torrevieja", provincia: "Alicante", zona: "Orihuela", activo: false },
]

// Serie de oportunidades detectadas (últimos 30 días).
export const serieOportunidades: PuntoSerie[] = (() => {
  const base = [
    2, 3, 3, 4, 3, 5, 4, 6, 5, 7, 6, 5, 8, 7, 9, 8, 6, 10, 9, 11, 8, 12, 10, 9,
    13, 11, 14, 12, 15, 13,
  ]
  return base.map((valor, i) => ({
    fecha: new Date(ahora - (base.length - 1 - i) * 86_400_000).toISOString(),
    valor,
  }))
})()

export const distribucionPerfiles: DistribucionPerfil[] = [
  { tipoPerfil: "Camareros", valor: 28 },
  { tipoPerfil: "Agricultura", valor: 22 },
  { tipoPerfil: "Cocineros", valor: 18 },
  { tipoPerfil: "Almacén", valor: 15 },
  { tipoPerfil: "Limpieza", valor: 14 },
  { tipoPerfil: "Construcción", valor: 12 },
  { tipoPerfil: "Administrativos", valor: 9 },
  { tipoPerfil: "Dependientes", valor: 5 },
  { tipoPerfil: "Otros", valor: 3 },
]

export const zonasActividad: ZonaActividad[] = [
  { zona: "Alicante", valor: 34 },
  { zona: "Elche", valor: 21 },
  { zona: "Murcia", valor: 18 },
  { zona: "Orihuela", valor: 12 },
  { zona: "Valencia", valor: 9 },
]
