import type {
  DistribucionPerfil,
  Empresa,
  Municipio,
  Notificacion,
  OtroPerfil,
  Oportunidad,
  Perfil,
  PuntoSerie,
  ZonaActividad,
} from "./types"

// Datos mock realistas. Al conectar Airtable, este archivo se sustituye por
// las llamadas a la API; la forma de los datos se mantiene igual.

const ahora = Date.UTC(2026, 8, 8, 12, 0, 0) // referencia estable para "hace X"

const hace = (minutos: number) => new Date(ahora - minutos * 60_000).toISOString()

export const oportunidades: Oportunidad[] = [
  {
    id: "opp_001",
    titulo: "Camarero/a de sala",
    empresa: "Grupo Mediterráneo",
    perfil: "Camarero/a",
    tipoPerfil: "Camareros",
    municipio: "Alicante",
    provincia: "Alicante",
    zona: "Alicante",
    urlOferta: "https://ejemplo.com/oferta/001",
    fuente: "InfoJobs",
    fechaPublicacion: hace(30),
    fechaDeteccion: hace(12),
    estado: "Nueva",
    prioridad: "Alta",
    descripcion:
      "Buscamos camarero/a con experiencia en sala para restaurante de alta ocupación en primera línea de playa. Jornada partida, fines de semana incluidos. Se valorá conocimiento de carta de vinos y atención en terraza.",
    notas: "",
  },
  {
    id: "opp_002",
    titulo: "Peón agrícola",
    empresa: "Agrícola Levante S.L.",
    perfil: "Peón agrícola",
    tipoPerfil: "Agricultura",
    municipio: "Elche",
    provincia: "Alicante",
    zona: "Elche",
    urlOferta: "https://ejemplo.com/oferta/002",
    fuente: "Milanuncios",
    fechaPublicacion: hace(60),
    fechaDeteccion: hace(26),
    estado: "Nueva",
    prioridad: "Media",
    descripcion:
      "Peón agrícola para tareas de recolección y manejo de cítricos. Trabajo a la intemperie, jornada completa. Se requiere resistencia física y disponibilidad para turnos de temporada.",
    notas: "",
  },
  {
    id: "opp_003",
    titulo: "Cocinero/a",
    empresa: "Hotel Costa Blanca",
    perfil: "Cocinero/a",
    tipoPerfil: "Cocineros",
    municipio: "Benidorm",
    provincia: "Alicante",
    zona: "Alicante",
    urlOferta: "https://ejemplo.com/oferta/003",
    fuente: "LinkedIn",
    fechaPublicacion: hace(120),
    fechaDeteccion: hace(60),
    estado: "Revisada",
    prioridad: "Alta",
    descripcion:
      "Cocinero/a para hotel de 4 estrellas con buffet y servicio de carta. Experiencia mínima de 3 años en cocina de volumen. Conocimientos de HACCP y alérgenos.",
    notas: "",
  },
  {
    id: "opp_004",
    titulo: "Mozo/a de almacén",
    empresa: "Logística Vega Sur",
    perfil: "Mozo/a de almacén",
    tipoPerfil: "Almacén",
    municipio: "Orihuela",
    provincia: "Alicante",
    zona: "Orihuela",
    urlOferta: "https://ejemplo.com/oferta/004",
    fuente: "InfoJobs",
    fechaPublicacion: hace(180),
    fechaDeteccion: hace(120),
    estado: "Contactada",
    prioridad: "Media",
    descripcion:
      "Mozo/a de almacén para preparación de pedidos, control de stock y carga/descarga de camiones. Carné de carretilla elevadora valorable. Turno de mañana.",
    notas: "",
  },
  {
    id: "opp_005",
    titulo: "Peón de construcción",
    empresa: "Construcciones Levante",
    perfil: "Peón construcción",
    tipoPerfil: "Construcción",
    municipio: "Murcia",
    provincia: "Murcia",
    zona: "Murcia",
    urlOferta: "https://ejemplo.com/oferta/005",
    fuente: "Indeed",
    fechaPublicacion: hace(200),
    fechaDeteccion: hace(180),
    estado: "Nueva",
    prioridad: "Alta",
    descripcion:
      "Peón de construcción para obra civil en el entorno de Murcia. Experiencia en acabados y demoliciones. EPI proporcionado. Contrato por obra o servicio.",
    notas: "",
  },
  {
    id: "opp_006",
    titulo: "Personal de limpieza",
    empresa: "Limpiezas Sol y Mar",
    perfil: "Limpiador/a",
    tipoPerfil: "Limpieza",
    municipio: "Alicante",
    provincia: "Alicante",
    zona: "Alicante",
    urlOferta: "https://ejemplo.com/oferta/006",
    fuente: "InfoJobs",
    fechaPublicacion: hace(260),
    fechaDeteccion: hace(240),
    estado: "Interesante",
    prioridad: "Media",
    descripcion:
      "Personal de limpieza para oficinas y comunidades de propietarios. Jornada de tarde, lunes a viernes. Experiencia previa en limpieza de mantenimiento.",
    notas: "",
  },
  {
    id: "opp_007",
    titulo: "Administrativo/a contable",
    empresa: "Gestoría Alba",
    perfil: "Administrativo/a",
    tipoPerfil: "Administrativos",
    municipio: "Elche",
    provincia: "Alicante",
    zona: "Elche",
    urlOferta: "https://ejemplo.com/oferta/007",
    fuente: "LinkedIn",
    fechaPublicacion: hace(300),
    fechaDeteccion: hace(280),
    estado: "Revisada",
    prioridad: "Baja",
    descripcion:
      "Administrativo/a con conocimientos de contabilidad y facturación. Manejo de programas de gestión. Atención al cliente presencial y telefónica.",
    notas: "",
  },
  {
    id: "opp_008",
    titulo: "Dependiente/a de tienda",
    empresa: "Moda Levante",
    perfil: "Dependiente/a",
    tipoPerfil: "Dependientes",
    municipio: "Valencia",
    provincia: "Valencia",
    zona: "Valencia",
    urlOferta: "https://ejemplo.com/oferta/008",
    fuente: "Indeed",
    fechaPublicacion: hace(360),
    fechaDeteccion: hace(320),
    estado: "Nueva",
    prioridad: "Media",
    descripcion:
      "Dependiente/a para tienda de moda en centro comercial. Experiencia en retail y reposición. Disponibilidad para fines de semana y horario partido.",
    notas: "",
  },
  {
    id: "opp_009",
    titulo: "Ayudante de cocina",
    empresa: "Restaurante El Puerto",
    perfil: "Ayudante de cocina",
    tipoPerfil: "Cocineros",
    municipio: "Alicante",
    provincia: "Alicante",
    zona: "Alicante",
    urlOferta: "https://ejemplo.com/oferta/009",
    fuente: "InfoJobs",
    fechaPublicacion: hace(420),
    fechaDeteccion: hace(400),
    estado: "Contactada",
    prioridad: "Media",
    descripcion:
      "Ayudante de cocina para restaurante de tapas en el puerto. Tareas de mise en place, limpieza de zona y apoyo al cocinero principal. Jornada partida.",
    notas: "",
  },
  {
    id: "opp_010",
    titulo: "Camarero/a de barra",
    empresa: "Cervecería Central",
    perfil: "Camarero/a",
    tipoPerfil: "Camareros",
    municipio: "Murcia",
    provincia: "Murcia",
    zona: "Murcia",
    urlOferta: "https://ejemplo.com/oferta/010",
    fuente: "Milanuncios",
    fechaPublicacion: hace(500),
    fechaDeteccion: hace(480),
    estado: "Nueva",
    prioridad: "Alta",
    descripcion:
      "Camarero/a de barra para cervecería de alto volumen. Manejo de caja, elaboración de raciones y atención rápida. Experiencia en hostelería de barra.",
    notas: "",
  },
  {
    id: "opp_011",
    titulo: "Operario/a de almacén",
    empresa: "Distribuciones Segura",
    perfil: "Operario/a",
    tipoPerfil: "Almacén",
    municipio: "Orihuela",
    provincia: "Alicante",
    zona: "Orihuela",
    urlOferta: "https://ejemplo.com/oferta/011",
    fuente: "Indeed",
    fechaPublicacion: hace(600),
    fechaDeteccion: hace(580),
    estado: "Revisada",
    prioridad: "Baja",
    descripcion:
      "Operario/a de almacén logístico con carretilla. Recepción de mercancía, picking y packing. Disponibilidad para turnos rotativos.",
    notas: "",
  },
  {
    id: "opp_012",
    titulo: "Recolector/a de cítricos",
    empresa: "Cítricos del Segura",
    perfil: "Peón agrícola",
    tipoPerfil: "Agricultura",
    municipio: "Orihuela",
    provincia: "Alicante",
    zona: "Orihuela",
    urlOferta: "https://ejemplo.com/oferta/012",
    fuente: "Milanuncios",
    fechaPublicacion: hace(720),
    fechaDeteccion: hace(700),
    estado: "Interesante",
    prioridad: "Alta",
    descripcion:
      "Recolector/a de cítricos para campaña de temporada. Trabajo manual al aire libre, con escaleras y cajas. Contrato temporal de 3 meses.",
    notas: "",
  },
  {
    id: "opp_013",
    titulo: "Encargado/a de limpieza",
    empresa: "Higiene Profesional Vega",
    perfil: "Encargado/a",
    tipoPerfil: "Limpieza",
    municipio: "Elche",
    provincia: "Alicante",
    zona: "Elche",
    urlOferta: "https://ejemplo.com/oferta/013",
    fuente: "InfoJobs",
    fechaPublicacion: hace(900),
    fechaDeteccion: hace(880),
    estado: "Nueva",
    prioridad: "Media",
    descripcion:
      "Encargado/a de equipo de limpieza industrial. Coordinación de personal, control de calidad y gestión de pedidos de productos. Experiencia en supervisión.",
    notas: "",
  },
  {
    id: "opp_014",
    titulo: "Recepcionista de hotel",
    empresa: "Hotel Marina Azul",
    perfil: "Recepcionista",
    tipoPerfil: "Administrativos",
    municipio: "Benidorm",
    provincia: "Alicante",
    zona: "Alicante",
    urlOferta: "https://ejemplo.com/oferta/014",
    fuente: "LinkedIn",
    fechaPublicacion: hace(1000),
    fechaDeteccion: hace(980),
    estado: "Contactada",
    prioridad: "Media",
    descripcion:
      "Recepcionista de hotel con idiomas (inglés e italiano). Turnos rotativos de mañana y tarde. Manejo de PMS y atención al huésped.",
    notas: "",
  },
  {
    id: "opp_015",
    titulo: "Peón de obra",
    empresa: "Edificaciones Sur",
    perfil: "Peón construcción",
    tipoPerfil: "Construcción",
    municipio: "Valencia",
    provincia: "Valencia",
    zona: "Valencia",
    urlOferta: "https://ejemplo.com/oferta/015",
    fuente: "Indeed",
    fechaPublicacion: hace(1200),
    fechaDeteccion: hace(1180),
    estado: "Descartada",
    prioridad: "Baja",
    descripcion:
      "Peón de obra para reformas interiores. Tareas de derribo, transporte de materiales y apoyo a oficiales. Experiencia mínima de 1 año.",
    notas: "",
  },
  {
    id: "opp_016",
    titulo: "Camarero/a de eventos",
    empresa: "Catering Mediterráneo",
    perfil: "Camarero/a",
    tipoPerfil: "Camareros",
    municipio: "Alicante",
    provincia: "Alicante",
    zona: "Alicante",
    urlOferta: "https://ejemplo.com/oferta/016",
    fuente: "InfoJobs",
    fechaPublicacion: hace(1400),
    fechaDeteccion: hace(1380),
    estado: "Nueva",
    prioridad: "Alta",
    descripcion:
      "Camarero/a de eventos y banquetes. Disponibilidad para fines de semana y horarios irregulares. Experiencia en servicio de catering y grandes eventos.",
    notas: "",
  },
  {
    id: "opp_017",
    titulo: "Mozo/a de carga y descarga",
    empresa: "Transportes Alicante",
    perfil: "Mozo/a",
    tipoPerfil: "Almacén",
    municipio: "Alicante",
    provincia: "Alicante",
    zona: "Alicante",
    urlOferta: "https://ejemplo.com/oferta/017",
    fuente: "Milanuncios",
    fechaPublicacion: hace(1600),
    fechaDeteccion: hace(1580),
    estado: "Revisada",
    prioridad: "Media",
    descripcion:
      "Mozo/a de carga y descarga para empresa de transportes. Manejo de transpaleta manual. Trabajo físico, jornada de mañana.",
    notas: "",
  },
  {
    id: "opp_018",
    titulo: "Dependiente/a de supermercado",
    empresa: "Supermercados Vega",
    perfil: "Dependiente/a",
    tipoPerfil: "Dependientes",
    municipio: "Elche",
    provincia: "Alicante",
    zona: "Elche",
    urlOferta: "https://ejemplo.com/oferta/018",
    fuente: "Indeed",
    fechaPublicacion: hace(1800),
    fechaDeteccion: hace(1780),
    estado: "Nueva",
    prioridad: "Media",
    descripcion:
      "Dependiente/a para supermercado con sección de frescos. Reposición, atención en caja y control de caducidades. Turnos rotativos.",
    notas: "",
  },
  {
    id: "opp_019",
    titulo: "Cocinero/a de línea",
    empresa: "Grupo Gastronómico Sur",
    perfil: "Cocinero/a",
    tipoPerfil: "Cocineros",
    municipio: "Murcia",
    provincia: "Murcia",
    zona: "Murcia",
    urlOferta: "https://ejemplo.com/oferta/019",
    fuente: "LinkedIn",
    fechaPublicacion: hace(2000),
    fechaDeteccion: hace(1980),
    estado: "Interesante",
    prioridad: "Alta",
    descripcion:
      "Cocinero/a de línea para grupo restaurativo con varias marcas. Especialización en cocina mediterránea y manejo de plancha. Experiencia de 2 años.",
    notas: "",
  },
  {
    id: "opp_020",
    titulo: "Auxiliar administrativo/a",
    empresa: "Asesoría Costa",
    perfil: "Administrativo/a",
    tipoPerfil: "Administrativos",
    municipio: "Valencia",
    provincia: "Valencia",
    zona: "Valencia",
    urlOferta: "https://ejemplo.com/oferta/020",
    fuente: "InfoJobs",
    fechaPublicacion: hace(2400),
    fechaDeteccion: hace(2380),
    estado: "Contactada",
    prioridad: "Baja",
    descripcion:
      "Auxiliar administrativo/a para asesoría fiscal y laboral. Gestión de documentos, atención al cliente y apoyo a gestores. Conocimientos de Ofimática.",
    notas: "",
  },
  {
    id: "opp_021",
    titulo: "Personal de limpieza industrial",
    empresa: "Servicios Vega",
    perfil: "Limpiador/a",
    tipoPerfil: "Limpieza",
    municipio: "Murcia",
    provincia: "Murcia",
    zona: "Murcia",
    urlOferta: "https://ejemplo.com/oferta/021",
    fuente: "Indeed",
    fechaPublicacion: hace(2800),
    fechaDeteccion: hace(2780),
    estado: "Nueva",
    prioridad: "Media",
    descripcion:
      "Personal de limpieza industrial para nave y maquinaria. Uo de productos específicos y maquinaria de presión. EPI obligatorio.",
    notas: "",
  },
  {
    id: "opp_022",
    titulo: "Peón agrícola de temporada",
    empresa: "Frutas del Mediterráneo",
    perfil: "Peón agrícola",
    tipoPerfil: "Agricultura",
    municipio: "Elche",
    provincia: "Alicante",
    zona: "Elche",
    urlOferta: "https://ejemplo.com/oferta/022",
    fuente: "Milanuncios",
    fechaPublicacion: hace(3200),
    fechaDeteccion: hace(3180),
    estado: "Revisada",
    prioridad: "Alta",
    descripcion:
      "Peón agrícola de temporada para poda y recolección de granadas y limones. Trabajo en finca, jornada completa a la intemperie.",
    notas: "",
  },
  {
    id: "opp_023",
    titulo: "Ayudante de camarero/a",
    empresa: "Chiringuito Playa Norte",
    perfil: "Ayudante",
    tipoPerfil: "Camareros",
    municipio: "Valencia",
    provincia: "Valencia",
    zona: "Valencia",
    urlOferta: "https://ejemplo.com/oferta/023",
    fuente: "InfoJobs",
    fechaPublicacion: hace(3600),
    fechaDeteccion: hace(3580),
    estado: "Nueva",
    prioridad: "Media",
    descripcion:
      "Ayudante de camarero/a para chiringuito de playa. Recogida de mesas, apoyo al camarero y limpieza de zona. Temporada de verano.",
    notas: "",
  },
  {
    id: "opp_024",
    titulo: "Repartidor/a con carné",
    empresa: "Mensajería Rápida Sur",
    perfil: "Repartidor/a",
    tipoPerfil: "Otros",
    municipio: "Alicante",
    provincia: "Alicante",
    zona: "Alicante",
    urlOferta: "https://ejemplo.com/oferta/024",
    fuente: "Indeed",
    fechaPublicacion: hace(4000),
    fechaDeteccion: hace(3980),
    estado: "Descartada",
    prioridad: "Baja",
    descripcion:
      "Repartidor/a con carné B para mensajería urgente. Conocimiento de la ciudad, disponibilidad inmediata y vehículo propio valorable.",
    notas: "",
  },
]

export const empresas: Empresa[] = [
  {
    id: "emp_001",
    nombre: "Grupo Mediterráneo",
    web: "grupomediterraneo.es",
    telefono: "965 12 34 56",
    email: "rrhh@grupomediterraneo.es",
    municipio: "Alicante",
    provincia: "Alicante",
    sector: "Hostelería",
    oportunidades: 6,
    estadoComercial: "En seguimiento",
    primeraDeteccion: hace(1380),
    ultimaActividad: hace(12),
    notas: "Cadena con 4 locales en Alicante ciudad. Contacto: Laura Pérez, RRHH. Interesados en servicio de catering para eventos corporativos.",
  },
  {
    id: "emp_002",
    nombre: "Agrícola Levante S.L.",
    web: "agricolalevante.com",
    telefono: "966 45 78 90",
    email: "empleo@agricolalevante.com",
    municipio: "Elche",
    provincia: "Alicante",
    sector: "Agricultura",
    oportunidades: 4,
    estadoComercial: "Sin contactar",
    primeraDeteccion: hace(3180),
    ultimaActividad: hace(26),
    notas: "Productora de cítricos y hortalizas. Contratación intensiva en campaña. Posible acuerdo de temporada.",
  },
  {
    id: "emp_003",
    nombre: "Hotel Costa Blanca",
    web: "hotelcostablanca.es",
    telefono: "965 88 77 66",
    email: "seleccion@hotelcostablanca.es",
    municipio: "Benidorm",
    provincia: "Alicante",
    sector: "Hostelería",
    oportunidades: 5,
    estadoComercial: "Cliente",
    primeraDeteccion: hace(1980),
    ultimaActividad: hace(60),
    notas: "Hotel de 4 estrellas, cliente activo desde 2024. Contratación recurrente para temporada alta.",
  },
  {
    id: "emp_004",
    nombre: "Logística Vega Sur",
    web: "logisticavegasur.com",
    telefono: "968 23 45 67",
    email: "rrhh@logisticavegasur.com",
    municipio: "Orihuela",
    provincia: "Alicante",
    sector: "Logística",
    oportunidades: 3,
    estadoComercial: "En seguimiento",
    primeraDeteccion: hace(580),
    ultimaActividad: hace(120),
    notas: "Plataforma logística en la Vega Baja. Demanda estable de mozos y carretilleros.",
  },
  {
    id: "emp_005",
    nombre: "Construcciones Levante",
    web: "construccioneslevante.es",
    telefono: "968 34 56 78",
    email: "empleo@construccioneslevante.es",
    municipio: "Murcia",
    provincia: "Murcia",
    sector: "Construcción",
    oportunidades: 4,
    estadoComercial: "Sin contactar",
    primeraDeteccion: hace(1180),
    ultimaActividad: hace(180),
    notas: "Empresa de construcción civil y reformas. Actividad en alza en el corredor Murcia-Alicante.",
  },
  {
    id: "emp_006",
    nombre: "Limpiezas Sol y Mar",
    web: "limpiezassolymar.com",
    telefono: "965 11 22 33",
    email: "info@limpiezassolymar.com",
    municipio: "Alicante",
    provincia: "Alicante",
    sector: "Servicios",
    oportunidades: 2,
    estadoComercial: "En seguimiento",
    primeraDeteccion: hace(880),
    ultimaActividad: hace(240),
    notas: "Empresa de limpieza de comunidades y oficinas. Contratación mensual.",
  },
  {
    id: "emp_007",
    nombre: "Gestoría Alba",
    web: "gestoriaalba.es",
    telefono: "966 55 44 33",
    email: "contacto@gestoriaalba.es",
    municipio: "Elche",
    provincia: "Alicante",
    sector: "Servicios",
    oportunidades: 1,
    estadoComercial: "Sin contactar",
    primeraDeteccion: hace(280),
    ultimaActividad: hace(280),
    notas: "Gestoría pequeña, contratación puntual de administrativos.",
  },
  {
    id: "emp_008",
    nombre: "Moda Levante",
    web: "modalevante.com",
    telefono: "963 22 11 44",
    email: "rrhh@modalevante.com",
    municipio: "Valencia",
    provincia: "Valencia",
    sector: "Comercio",
    oportunidades: 2,
    estadoComercial: "Sin contactar",
    primeraDeteccion: hace(320),
    ultimaActividad: hace(320),
    notas: "Cadena de moda con 6 tiendas en Valencia y Alicante. Contratación de temporada.",
  },
  {
    id: "emp_009",
    nombre: "Cítricos del Segura",
    web: "citricosdelsegura.es",
    telefono: "968 77 88 99",
    email: "empleo@citricosdelsegura.es",
    municipio: "Orihuela",
    provincia: "Alicante",
    sector: "Agricultura",
    oportunidades: 3,
    estadoComercial: "En seguimiento",
    primeraDeteccion: hace(700),
    ultimaActividad: hace(700),
    notas: "Exportador de cítricos. Alta demanda en invierno y primavera.",
  },
  {
    id: "emp_010",
    nombre: "Distribuciones Segura",
    web: "distribucionessegura.com",
    telefono: "968 66 55 44",
    email: "rrhh@distribucionessegura.com",
    municipio: "Orihuela",
    provincia: "Alicante",
    sector: "Logística",
    oportunidades: 2,
    estadoComercial: "Cliente",
    primeraDeteccion: hace(580),
    ultimaActividad: hace(580),
    notas: "Distribuidora de alimentación. Cliente desde 2023.",
  },
  {
    id: "emp_011",
    nombre: "Catering Mediterráneo",
    web: "cateringmediterraneo.es",
    telefono: "965 99 88 77",
    email: "seleccion@cateringmediterraneo.es",
    municipio: "Alicante",
    provincia: "Alicante",
    sector: "Hostelería",
    oportunidades: 3,
    estadoComercial: "En seguimiento",
    primeraDeteccion: hace(1380),
    ultimaActividad: hace(1380),
    notas: "Empresa de catering para bodas y eventos. Picos de demanda en primavera y verano.",
  },
  {
    id: "emp_012",
    nombre: "Supermercados Vega",
    web: "supermercadosvega.com",
    telefono: "966 33 22 11",
    email: "empleo@supermercadosvega.com",
    municipio: "Elche",
    provincia: "Alicante",
    sector: "Comercio",
    oportunidades: 2,
    estadoComercial: "Sin contactar",
    primeraDeteccion: hace(1780),
    ultimaActividad: hace(1780),
    notas: "Franquicia de supermercados. Contratación continua de dependientes y reponedores.",
  },
  {
    id: "emp_013",
    nombre: "Grupo Gastronómico Sur",
    web: "grupogastronomicosur.es",
    telefono: "968 44 33 22",
    email: "rrhh@grupogastronomicosur.es",
    municipio: "Murcia",
    provincia: "Murcia",
    sector: "Hostelería",
    oportunidades: 4,
    estadoComercial: "Cliente",
    primeraDeteccion: hace(1980),
    ultimaActividad: hace(1980),
    notas: "Grupo con 3 restaurantes en Murcia. Cliente recurrente.",
  },
  {
    id: "emp_014",
    nombre: "Frutas del Mediterráneo",
    web: "frutasmediterraneo.com",
    telefono: "966 22 33 44",
    email: "temporada@frutasmediterraneo.com",
    municipio: "Elche",
    provincia: "Alicante",
    sector: "Agricultura",
    oportunidades: 5,
    estadoComercial: "En seguimiento",
    primeraDeteccion: hace(3180),
    ultimaActividad: hace(3180),
    notas: "Productora y envasadora de fruta. Contratación masiva en campaña de granada.",
  },
]

export const perfiles: Perfil[] = [
  { id: "per_001", nombre: "Limpieza", activo: true },
  { id: "per_002", nombre: "Camareros", activo: true },
  { id: "per_003", nombre: "Cocineros", activo: true },
  { id: "per_004", nombre: "Administrativos", activo: true },
  { id: "per_005", nombre: "Almacén", activo: true },
  { id: "per_006", nombre: "Dependientes", activo: true },
  { id: "per_007", nombre: "Agricultura", activo: true },
  { id: "per_008", nombre: "Construcción", activo: true },
  { id: "per_009", nombre: "Otros", activo: false },
]

export const otrosPerfiles: OtroPerfil[] = [
  {
    id: "otr_001",
    nombre: "Repartidor/a",
    oportunidades: 4,
    empresas: 2,
    ultimaDeteccion: hace(3980),
  },
  {
    id: "otr_002",
    nombre: "Jardinero/a",
    oportunidades: 2,
    empresas: 1,
    ultimaDeteccion: hace(5200),
  },
  {
    id: "otr_003",
    nombre: "Técnico/a de mantenimiento",
    oportunidades: 3,
    empresas: 2,
    ultimaDeteccion: hace(6400),
  },
  {
    id: "otr_004",
    nombre: "Conductor/a",
    oportunidades: 2,
    empresas: 1,
    ultimaDeteccion: hace(7800),
  },
  {
    id: "otr_005",
    nombre: "Recepcionista",
    oportunidades: 1,
    empresas: 1,
    ultimaDeteccion: hace(980),
  },
  {
    id: "otr_006",
    nombre: "Operario/a de producción",
    oportunidades: 2,
    empresas: 1,
    ultimaDeteccion: hace(4200),
  },
]

export const municipios: Municipio[] = [
  { id: "mun_001", municipio: "Alicante", provincia: "Alicante", zona: "Alicante", activo: true },
  { id: "mun_002", municipio: "Elche", provincia: "Alicante", zona: "Elche", activo: true },
  { id: "mun_003", municipio: "Orihuela", provincia: "Alicante", zona: "Orihuela", activo: true },
  { id: "mun_004", municipio: "Benidorm", provincia: "Alicante", zona: "Alicante", activo: true },
  { id: "mun_005", municipio: "Murcia", provincia: "Murcia", zona: "Murcia", activo: true },
  { id: "mun_006", municipio: "Valencia", provincia: "Valencia", zona: "Valencia", activo: true },
  { id: "mun_007", municipio: "Torrevieja", provincia: "Alicante", zona: "Orihuela", activo: false },
]

// Serie de oportunidades detectadas (últimos 30 días, evolución diaria).
export const serieOportunidades30d: PuntoSerie[] = (() => {
  const base = [
    2, 3, 3, 4, 3, 5, 4, 6, 5, 7, 6, 5, 8, 7, 9, 8, 6, 10, 9, 11, 8, 12, 10, 9,
    13, 11, 14, 12, 15, 13,
  ]
  return base.map((valor, i) => ({
    fecha: new Date(ahora - (base.length - 1 - i) * 86_400_000).toISOString(),
    valor,
  }))
})()

// Serie de los últimos 7 días (evolución diaria).
export const serieOportunidades7d: PuntoSerie[] = (() => {
  const base = [9, 11, 8, 12, 10, 13, 15]
  return base.map((valor, i) => ({
    fecha: new Date(ahora - (base.length - 1 - i) * 86_400_000).toISOString(),
    valor,
  }))
})()

// Serie de hoy (evolución por horas).
export const serieOportunidadesHoy: PuntoSerie[] = (() => {
  const base = [1, 0, 2, 1, 0, 1, 3, 2, 1, 2, 3, 2, 4]
  return base.map((valor, i) => ({
    fecha: new Date(ahora - (base.length - 1 - i) * 3_600_000).toISOString(),
    valor,
  }))
})()

export const distribucionPerfiles: DistribucionPerfil[] = [
  { tipoPerfil: "Camareros", valor: 28 },
  { tipoPerfil: "Agricultura", valor: 22 },
  { tipoPerfil: "Cocineros", valor: 18 },
  { tipoPerfil: "Almacén", valor: 15 },
  { tipoPerfil: "Limpieza", valor: 14 },
  { tipoPerfil: "Construcción", valor: 12 },
  { tipoPerfil: "Administrativos", valor: 9 },
  { tipoPerfil: "Dependientes", valor: 5 },
  { tipoPerfil: "Otros", valor: 3 },
]

export const zonasActividad: ZonaActividad[] = [
  { zona: "Alicante", valor: 34 },
  { zona: "Elche", valor: 21 },
  { zona: "Murcia", valor: 18 },
  { zona: "Orihuela", valor: 12 },
  { zona: "Valencia", valor: 9 },
]

export const notificaciones: Notificacion[] = [
  {
    id: "not_001",
    texto: "8 nuevas oportunidades detectadas",
    tiempo: "Hace 12 min",
    leida: false,
    tipo: "oportunidad",
  },
  {
    id: "not_002",
    texto: "Nueva empresa detectada en Elche",
    tiempo: "Hace 26 min",
    leida: false,
    tipo: "empresa",
  },
  {
    id: "not_003",
    texto: "Agricultura aumenta su actividad",
    tiempo: "Hace 1 h",
    leida: false,
    tipo: "perfil",
  },
  {
    id: "not_004",
    texto: "Actualización completada correctamente",
    tiempo: "Hace 2 h",
    leida: true,
    tipo: "sistema",
  },
]
